baseURL: 'https://arthurjordao.dev/'
languageCode: en-us
title: Arthur Jord達o
theme: personal-theme

enableRobotsTXT: true

minify:
  disableXML: false
  minifyOutput: true

params:
  env: production
  description: Arthur Jord達o - Software made simple
  profileMode:
    enabled: true
    subtitle: "Software made simple"
    description: Arthur Jord達o personal website. Software made simple.
    imageUrl: "images/pp.webp"
    imageTitle: "My photo"
    buttons:
        - name: About me
          url: /about
  keywords:
    - blog
    - software engineering
    - Arthur Jord達o
    - compilers
  ShowReadingTime: true
  mainSections:
    - about
  socialIcons:
    - name: "github"
      url: "https://github.com/ArthurJordao"
    - name: "twitter"
      url: "https://twitter.com/_ArthurJordao"
    - name: "youtube"
      url: "https://www.youtube.com/channel/UC9GfddKP0AFtoSoAXsr5fCw"
    - name: "linkedin"
      url: "https://linkedin.com/in/arthurjordao/"
    - name: "instagram"
      url: "https://instagram.com/arthurbjordao"
    - name: "email"
      url: "mailto:hi@arthurjordao.dev"
    - name: "mastodon"
      url: "https://bolha.us/@arthurjordao"
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About me
          url: /about
        - name: Posts
          url: /posts
