baseURL: 'https://arthurjordao.dev/'
languageCode: en-us
title: Arthur Jordão
theme: personal-theme

enableRobotsTXT: true

minify:
  disableXML: false
  minifyOutput: true

googleAnalytics: G-3BJ3FNSC1K

params:
  env: production
  profileMode:
    enabled: true
    subtitle: "Software made simple"
    description: Arthur Jordão personal website. Software made simple.
    imageUrl: "images/pp.webp"
    imageTitle: "My photo"
    buttons:
        - name: About me
          url: /about
  keywords:
    - blog
    - software engineering
    - Arthur Jordão
    - compilers
  ShowReadingTime: true
  mainSections:
    - about
  socialIcons:
    - name: "github"
      url: "https://github.com/ArthurJordao"
    - name: "twitter"
      url: "https://twitter.com/_ArthurJordao"
    - name: "youtube"
      url: "https://www.youtube.com/channel/UC9GfddKP0AFtoSoAXsr5fCw"
    - name: "linkedin"
      url: "https://linkedin.com/in/arthurjordao/"
    - name: "instagram"
      url: "https://instagram.com/arthurbjordao"
    - name: "email"
      url: "mailto:hi@arthurjordao.dev"
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About me
          url: /about


