/**
 * Renders src/data/cv.ts into the plain text LinkedIn's fields accept.
 *
 * The output is committed, not built into dist/, because its value is the
 * `git diff` after a CV change: that diff is the list of fields to paste.
 *
 * LinkedIn's own limits, which this stays inside: About caps at 2,600
 * characters and each position description at 2,000. scripts/check-cv.sh
 * asserts both.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { cv, parseMonth, skills } from "../src/data/cv.ts";

const OUT = "content/cv/linkedin-paste.txt";

/** Month spelled out, which is the form LinkedIn's own date fields show. */
const formatMonth = (month: string) =>
	parseMonth(month).toLocaleDateString("en-US", {
		month: "long",
		timeZone: "UTC",
		year: "numeric",
	});

const lines: string[] = [
	"# Generated by `npm run cv:linkedin` from src/data/cv.ts. Do not edit by hand.",
	"# Paste each section into the matching LinkedIn field. The git diff of this",
	"# file after a CV change is the list of fields that need pasting.",
	"",
	"## HEADLINE",
	`${cv.basics.title} | ${cv.basics.tagline}`,
	"",
	"## ABOUT",
	cv.summary,
	"",
	"## EXPERIENCE",
];

for (const position of cv.positions) {
	const end = position.end ? formatMonth(position.end) : "Present";
	lines.push(
		"",
		`### ${position.company}`,
		`Title: ${position.title}`,
		`Dates: ${formatMonth(position.start)} — ${end}`,
		`Location: ${position.location}`,
		"",
		position.summary,
		"",
		...position.highlights.map((highlight) => `• ${highlight}`),
		"",
		`Skills: ${[...new Set(position.tech)].join(", ")}`,
	);
}

lines.push("", "## EDUCATION");
for (const entry of cv.education) {
	lines.push(`${entry.institution} — ${entry.qualification} (${entry.start} — ${entry.end})`);
}

lines.push("", "## SKILLS");
lines.push(...skills);

lines.push("", "## LANGUAGES");
for (const entry of cv.languages) {
	lines.push(`${entry.language} — ${entry.level}`);
}

lines.push("");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`wrote ${OUT}`);
